USE SAP_DIV
GO
CREATE TABLE VALOR_AJUSTE (
MATERIAL varchar(20), 
CENTRO varchar(5), 
DEPOSITO varchar(5), 
TIPO_DE_MOVIMENTO varchar(5),
ESTOQUE_ESPECIAL varchar(20), 
DOC_MATERIAL varchar(20), 
ITEM_DOC_MATERIAL INT,
DATA_DE_LANÇAMENTO DATE, 
QTD___UM_REGISTRO INT, 
UM_REGISTRO varchar(10), 
MONTANTE_EM_MI numeric(12,2), 
MONTANTE_EXTERNO_EM_MI INT, 
FORNECEDOR varchar(50), 
REFERENCIA varchar(50));

SELECT * FROM VALOR_AJUSTE;