USE SAP_DIV 
GO
CREATE TABLE AUSP (
    OBJEK VARCHAR (15),
    ATWRT VARCHAR (15));


SELECT * FROM AUSP;

ALTER TABLE AUSP ALTER COLUMN OBJEK VARCHAR(15) NOT NULL
ALTER TABLE AUSP ADD CONSTRAINT PK_OBJEK PRIMARY KEY (OBJEK)
ALTER TABLE AUSP ADD CONSTRAINT FK_OBJEK FOREIGN KEY (OBJEK) REFERENCES KNA1 (KUNNR);