USE SAP_BSEG
GO
CREATE TABLE BSEG (
BUKRS VARCHAR(4),
BELNR VARCHAR(10),
GJAHR VARCHAR(4),
BUZEI VARCHAR(3),
BUZID VARCHAR(1),
AUGDT DATE,
AUGCP DATE,
AUGBL VARCHAR(10),
BSCHL VARCHAR(2),
KOART VARCHAR(1),
SHKZG VARCHAR(1),
MWSKZ VARCHAR(2),
DMBTR NUMERIC(10,2),
WRBTR NUMERIC(10,2),
ZUONR VARCHAR(18),
SGTXT VARCHAR(50),
KOSTL VARCHAR(10),
VBELN VARCHAR(10),
VBEL2 VARCHAR(10),
POSN2 VARCHAR(6),
HKONT VARCHAR(10),
KUNNR VARCHAR(10),
LIFNR VARCHAR(10),
ZTERM VARCHAR(4),
HBKID VARCHAR(5),
MATNR VARCHAR(14),
WERKS VARCHAR(4),
MENGE VARCHAR(8),
EBELN VARCHAR(10),
EBELP VARCHAR(5),
BWKEY VARCHAR(4),
CESSION_KZ VARCHAR(2),
KSTAR VARCHAR(10));


DELETE FROM BSEG