USE query_dw
GO

ALTER VIEW view_ATENDIMENTO_HISTORICO_2_2
AS
	SELECT 
					c.MATR as 'MATR_CLIENTE',
					c.CLIENTE as 'CLIENTE',
					p.NETWR+p.KZWI1 as 'VALOR_FAT',
					p.KZWI4 as 'VALOR FRETE',
					p.FKIMG as 'QF',
					p.GSBER as 'CENTRO',
					k.XBLNR as 'NF',
					k.REGIO as 'REGIAO',
					p.VGBEL as 'REMESSA',
					p.AUBEL as 'OV',
					p.MATNR as 'MATERIAL',
					k.INCO2 as 'CIDADE',
					p.ARKTX as 'DESC',
					k.FKDAT as 'DATA_FAT',
					p.TXJCD as 'COD_IBGE',
					isnull(e.EBELN, 0) as 'PEDIDO_TRANSFE',
					isnull(e.MENGE, 0) as 'QTDE_TRANSFERIDO',
					isnull(e.BWART, 0) as 'TIPO_MOVIMENTO',
					kko.RESWK as 'ORIGEM'
	FROM		(SELECT REGIO, INCO2, FKDAT, FKART, FKSTO, SFAKN, KUNRG, VBELN, XBLNR  FROM unifort_prod.dbo.VBRK WHERE ERDAT >=  '01/12/2022' and FKART = 'F2B' and FKSTO = '' and SFAKN = '') k
	left join	(SELECT NETWR, KZWI1, KZWI4, FKIMG, GSBER, VGBEL, AUBEL, MATNR, ARKTX, TXJCD ,VBELN FROM SAP_VBRP.dbo.VBRP WHERE ERDAT >= '01/12/2022' ) p ON (p.VBELN = k.VBELN)
	left join	unifort_prod.dbo.view_dados_cliente_dw c ON (k.KUNRG = c.MATR)
	left join	(SELECT	DISTINCT EBELN, MATNR, AFNAM, NETPR, MAX(AEDAT)	AEDAT FROM unifort_prod.dbo.EKPO WHERE LOEKZ != 'L' and AFNAM != '' GROUP BY EBELN, MATNR, AFNAM, NETPR) o ON (p.AUBEL = o.AFNAM) and (p.MATNR = o.MATNR)
	left join	(SELECT DISTINCT ee.MENGE, ee.BWART, ee.EBELN, ee.MATNR, ee.BUDAT FROM unifort_prod.dbo.EKBE ee WHERE BWART = '861' AND ee.BUDAT > '01/12/2022') e ON (o.EBELN = e.EBELN) and (o.MATNR = e.MATNR)
	left join	(SELECT DISTINCT ko.EBELN, ko.RESWK FROM unifort_prod.dbo.EKKO ko WHERE ko.RESWK != '') kko ON (e.EBELN =  kko.EBELN)
GO

			
			
			
SELECT cn.CONHECIMENTO, cn.ID_PARCEIRO, cn.VALOR_TOT_NOTA, cn.ORDEM_VENDA ,cn.TIPO_PARCEIRO, cn.NUMERO_NF, cn.DATA_EMISS_CON FROM SAP_DIV.dbo.ZMMT_CONHEC_NOTA cn WHERE cn.TIPO_PARCEIRO = 'C'
SELECT cn.CONHECIMENTO, cn.ID_PARCEIRO, cn.VALOR_TOT_NOTA, cn.ORDEM_VENDA ,cn.TIPO_PARCEIRO, cn.NUMERO_NF, cn.DATA_EMISS_CON FROM SAP_DIV.dbo.ZMMT_CONHEC_NOTA cn WHERE cn.TIPO_PARCEIRO = 'B'
SELECT c.FATURA, c.CONHECIMENTO FROM SAP_DIV.dbo.ZMMT_FAT_CONHE c


SELECT * FROM ATENDIMENTO_HISTORICO_E_FILIAL_2_2


