CREATE TABLE mlov_consultcort(
NROCARGA VARCHAR(15),
DATA_CORTE DATE,
SEQPRODUTO VARCHAR(10), 
QTDEMBALAGEM INT,
QTDEMBSOLICITADA INT,
QTDEMBSEPARADA INT,
QTDDIVERGENTE INT,
MOTDIVERGEXPED VARCHAR(50),
CODPRODUTIVO VARCHAR(15),
PRODUTIVO VARCHAR(150), 
REMESSA VARCHAR(30), 
ORDEM VARCHAR (15)
);

DELETE FROM CORTE
WHERE DATA_CORTE >= '01/10/2022';



USE WMS_DIV
GO
SELECT		FORMAT(DATA_CORTE,  'dd/MM/yyyy', 'pt-BR') AS 'DATA',
			COUNT(DATA_CORTE)
			FROM CORTE
		WHERE DATA_CORTE >= '01/10/2022'
		GROUP BY FORMAT(DATA_CORTE,  'dd/MM/yyyy', 'pt-BR');


