CREATE TABLE unifort_prod.dbo.KNA1 (
MANDT VARCHAR(50),
KUNNR VARCHAR(50),
LAND1 VARCHAR(50),
NAME1 VARCHAR(50),
NAME2 VARCHAR(50),
ORT01 VARCHAR(50),
PSTLZ VARCHAR(50),
REGIO VARCHAR(50),
SORTL VARCHAR(50),
STRAS VARCHAR(50),
TELF1 VARCHAR(50),
TELFX VARCHAR(50),
ADRNR VARCHAR(50),
MCOD1 VARCHAR(50),
MCOD2 VARCHAR(50),
MCOD3 VARCHAR(50),
ANRED VARCHAR(50),
AUFSD VARCHAR(50),
BAHNE VARCHAR(50),
BAHNS VARCHAR(50),
BBBNR VARCHAR(50),
BBSNR VARCHAR(50),
BRSCH VARCHAR(50),
BUBKZ VARCHAR(50),
ERDAT VARCHAR(50),
ERNAM VARCHAR(50),
KTOKD VARCHAR(50),
LIFNR VARCHAR(50),
LOCCO VARCHAR(50),
LOEVM VARCHAR(50),
NAME3 VARCHAR(50),
NAME4 VARCHAR(50),
ORT02 VARCHAR(50),
PFACH VARCHAR(50),
SPERR VARCHAR(50),
SPRAS VARCHAR(50),
STCD1 VARCHAR(50),
STCD2 VARCHAR(50),
TELF2 VARCHAR(50),
LZONE VARCHAR(50),
UMSAT VARCHAR(50),
UMJAH VARCHAR(50),
JMZAH VARCHAR(50),
JMJAH VARCHAR(50),
STKZN VARCHAR(50),
UMSA1 VARCHAR(50),
TXJCD VARCHAR(50),
DUEFL VARCHAR(50),
HZUOR VARCHAR(50),
CIVVE VARCHAR(50),
STCD3 VARCHAR(50),
STCD4 VARCHAR(50),
XICMS VARCHAR(50),
XXIPI VARCHAR(50),
XSUBT VARCHAR(50),
CFOPC VARCHAR(50),
CASSD VARCHAR(50),
UPTIM VARCHAR(50),
NODEL VARCHAR(50),
RIC VARCHAR(50),
CNAE VARCHAR(50),
LEGALNAT VARCHAR(50),
VSOR_PALHGT VARCHAR(50),
VSOR_I_NO_LYR VARCHAR(50),
VSOR_ULD_SIDE VARCHAR(50),
VSOR_LOAD_PREF VARCHAR(50),
ZZINFST VARCHAR(50));

select TOP(50) * from unifort_prod.dbo.KNA1;



/* 
-------------------------------------- CRIAÇÃO DE QUERY -----------------------------------------------
*/
-- QUERY COM DADOS DO CLIENTE ALVARO

USE	unifort_prod
GO
ALTER VIEW view_dados_cliente_dw
AS
SELECT			KUNNR as 'MATR',
				NAME1 as 'CLIENTE',
				ORT01 as 'CIDADE', 
				REGIO as 'UF',
				MCOD1 as 'NOME FANTASIA',
				STRAS as 'ENDEREÇO',
				ORT02 as 'BAIRRO',
				PSTLZ as 'CEP',
				STCD1 as 'CNPJ',
				TELF1 as 'TELEFONE1',
				TELF2 as 'TELEFONE2',
				TELFX as 'TELEFONE_FAX'
				from unifort_prod.dbo.KNA1
GO



SELECT * FROM view_dados_cliente_dw;