SELECT * FROM KNA1;
SELECT * FROM AUSP;


ALTER TABLE KNA1 ALTER COLUMN KUNNR VARCHAR(15) NOT NULL;
ALTER TABLE KNA1 ADD CONSTRAINT PK_KUNNR PRIMARY KEY (KUNNR);
ALTER TABLE KNA1 ADD CONSTRAINT PK_KUNNR PRIMARY KEY (KUNNR);

