SELECT *  FROM [SAP_DIV].[dbo].[LFA1];

SELECT * FROM LFA1
ALTER TABLE LFA1 ALTER COLUMN ERDAT DATE;
ALTER TABLE LFA1 ALTER COLUMN LIFNR VARCHAR(15) NOT NULL;
ALTER TABLE LFA1 ADD CONSTRAINT PF_LIFNR PRIMARY KEY (LIFNR);


