CREATE TABLE mlov_produtivoseparacao (
NOME VARCHAR(100),
DATA DATETIME,
ATIVIDADE VARCHAR(50),
ESP VARCHAR(15),
ATIVIDAD INT,
TAREFAS INT,
QTDVOL NUMERIC(6,2)
);

SELECT MAX(DATA) FROM mlov_produtivoseparacao;
