CREATE TABLE mlov_relatorioenderecos (
SEQPRODUTO VARCHAR(20), 
DESCCOMPLETA VARCHAR(100), 
ESPECIEENDERECO VARCHAR(10), 
INDTERREOAEREO VARCHAR(10),
ENDERECO VARCHAR(20), 
STATUSENDERECO VARCHAR(10), 
QTDEMBALAGEM INT, 
QTDATUAL INT, 
NORMA VARCHAR(20),
OCUPACAO INT, 
DATA_REL DATETIME
);



SELECT MAX(DATA_REL) FROM WMS_DIV.dbo.mlov_relatorioenderecos;



SELECT * FROM WMS_DIV.dbo.mlov_relatorioenderecos
WHERE DATA_REL >= (SELECT MAX(DATA_REL) FROM WMS_DIV.dbo.mlov_relatorioenderecos);
