USE query_dw
GO
CREATE TABLE MUNICIPIOS_LAT_LONG (
CD_GEOCODMU VARCHAR(12),
NM_MUNICIPIO VARCHAR(37),
NM_MICRO VARCHAR(41),
NM_MESO VARCHAR(39),
NM_UF VARCHAR(24),
CD_CATEGORIA VARCHAR(6),
NM_CATEGORIA VARCHAR(11),
NM_LOCALIDADE VARCHAR(37),
LONG FLOAT,
LAT FLOAT);
