USE WMS_DIV
GO
CREATE TABLE TEMPO_ARMAZENAGEM(
[NROCARGARECEB] VARCHAR(5),
[PESO_ARMAZ] NUMERIC(10,2),
[M3_ARMAZ] NUMERIC(10,2),
[QTDVOL_ARMAZ] INT,
[SKUS_ARMAZ] INT,
[DATACONF] DATE,
[HORACONF] TIME,
[DATAARMAZ] DATE,
[HORAARMAZ] TIME);