SELECT YEAR(AUDAT) ANO,
		MONTH(AUDAT) MES,
		COUNT(AUDAT) 
	FROM SAP_DIV.dbo.VAKPA
	GROUP BY YEAR(AUDAT), MONTH(AUDAT)
	ORDER BY YEAR(AUDAT), MONTH(AUDAT);

(SELECT KUNDE,NAME1 FROM (SELECT * FROM SAP_DIV.dbo.VAKPA WHERE PARVW = 'SP') pa
	left join (SELECT * FROM SAP_DIV.dbo.LFA1) a ON (a.LIFNR = pa.KUNDE));

SELECT * FROM SAP_DIV.dbo.VAKPA


SELECT	
			v.VBELN 'OV',
			v.KUNDE 'MATR VE',
			a.KUNDE 'MATR SP',
			p.KUNDE 'MATR VP',
			g.KUNDE 'MATR AG'
		FROM 
	(SELECT VBELN, KUNDE FROM SAP_DIV.dbo.VAKPA WHERE AUDAT >= '01/09/2022' AND PARVW = 'VE') v
	left join (SELECT KUNDE, VBELN FROM SAP_DIV.dbo.VAKPA WHERE AUDAT >= '01/09/2022' AND PARVW = 'SP') a ON (v.VBELN = a.VBELN)
	left join (SELECT KUNDE, VBELN FROM SAP_DIV.dbo.VAKPA WHERE AUDAT >= '01/09/2022' AND PARVW = 'VP') p ON (v.VBELN = a.VBELN)
	left join (SELECT KUNDE, VBELN FROM SAP_DIV.dbo.VAKPA WHERE AUDAT >= '01/09/2022' AND PARVW = 'AG') g ON (v.VBELN = a.VBELN)




USE unifort_prod
GO
ALTER VIEW view_nome_trans_pa_OV
AS
SELECT	
			v.VBELN 'OV',
			v.KUNDE 'MATR_PA',
			a.KUNDE 'MATR_SP'
		FROM 
	(SELECT VBELN, KUNDE FROM SAP_DIV.dbo.VAKPA WHERE AUDAT >= '01/09/2022' AND PARVW = 'VP') v
	left join (SELECT KUNDE, VBELN FROM SAP_DIV.dbo.VAKPA WHERE AUDAT >= '01/09/2022' AND PARVW = 'SP') a ON (v.VBELN = a.VBELN)

select * from view_nome_trans_pa_OV