USE SAP_DIV
GO
ALTER TABLE SAP_DIV.[dbo].ZMM020 ALTER COLUMN ULT_ANDAMENTO varchar(2600) NULL;
ALTER TABLE SAP_DIV.[dbo].ZMM020 ALTER COLUMN OCORRENCIA_1 varchar(25) NULL;
ALTER TABLE SAP_DIV.[dbo].ZMM020 ALTER COLUMN CLIENTE varchar(20) NULL;
ALTER TABLE SAP_DIV.[dbo].ZMM020 ALTER COLUMN HR_LIG TIME;
ALTER TABLE SAP_DIV.[dbo].ZMM020 ALTER COLUMN NOME_1 varchar(45) NULL;


USE SAP_DIV
GO
SELECT * FROM ZMM020;

