USE ZMM1237
GO
SELECT		zt.AEDAT
			,zt.MATNR
			,COALESCE(qm.QTDE_CLIENTE, 0) QTDE_CLIENTE
			,zt.MAABC
			,zt.LABOR
			,zt.QTDE_EMBALAGEM_A
			,zt.QTDE_EMBALAGEM_M
			,zt.QTDE_EMBALAGEM_P
			,zt.PERC_EMBALAGEM_A
			,zt.PERC_EMBALAGEM_M
			,zt.PERC_EMBALAGEM_P
			FROM ZMMT017  zt
		LEFT JOIN query_dw.dbo.view_qtde_cliente_por_material qm ON (zt.MATNR = qm.MATERIAL)
GO


USE query_dw
GO
CREATE VIEW view_qtde_cliente_por_material
AS
	SELECT		[MATERIAL]
				,COUNT(DISTINCT([MATR_CLIENTE])) QTDE_CLIENTE
			FROM query_dw.dbo.ANALISE_HISTORICA_VENDA 
		WHERE DATA_FAT >= DATEADD(DAY,-365, (SELECT MAX(DATA_FAT) FROM query_dw.dbo.ANALISE_HISTORICA_VENDA WHERE DATA_FAT >= '01/10/2022'))
		GROUP BY [MATERIAL]
GO
