USE SAP_DIV
GO
SELECT YEAR(DATA_EMIS_NOTA) ANO,
		MONTH(DATA_EMIS_NOTA) MES,
		COUNT(DATA_EMIS_NOTA) QTD
	FROM SAP_DIV.dbo.ZMMT_CONHEC_NOTA
	WHERE DATA_EMIS_NOTA >= '01/01/2022'
	GROUP BY YEAR(DATA_EMIS_NOTA), MONTH(DATA_EMIS_NOTA)
	ORDER BY YEAR(DATA_EMIS_NOTA), MONTH(DATA_EMIS_NOTA);

SELECT * FROM ZMMT_CONHEC_NOTA

ALTER TABLE SAP_DIV.dbo.ZMMT_CONHEC_NOTA ALTER COLUMN DATA_EMIS_NOTA DATE;
ALTER TABLE SAP_DIV.dbo.ZMMT_CONHEC_NOTA ALTER COLUMN DATA_EMISS_CON DATE;

ALTER TABLE SAP_DIV.dbo.ZMMT_CONHEC_NOTA ALTER COLUMN VALOR_OV NUMERIC(10,2);
ALTER TABLE SAP_DIV.dbo.ZMMT_CONHEC_NOTA ALTER COLUMN VALOR_FRETE_RAT NUMERIC(10,2);
ALTER TABLE SAP_DIV.dbo.ZMMT_CONHEC_NOTA ALTER COLUMN VALOR_ICMS_RAT NUMERIC(10,2);
ALTER TABLE SAP_DIV.dbo.ZMMT_CONHEC_NOTA ALTER COLUMN VALOR_ST_RAT NUMERIC(10,2);
ALTER TABLE SAP_DIV.dbo.ZMMT_CONHEC_NOTA ALTER COLUMN VALOR_TOT_NOTA NUMERIC(10,2);
ALTER TABLE SAP_DIV.dbo.ZMMT_CONHEC_NOTA ALTER COLUMN VALOR_FRETE_INCL NUMERIC(10,2);


USE SAP_DIV
GO
SELECT	CONHECIMENTO, ORDEM_VENDA, DATA_EMISS_CON, DATA_EMIS_NOTA, VALOR_TOT_NOTA, VALOR_FRETE_RAT as 'FRETE_TRANSFERENCIA',
TIPO_PARCEIRO FROM SAP_DIV.dbo.ZMMT_CONHEC_NOTA  WHERE DATA_EMIS_NOTA >= '01/01/2022' and TIPO_PARCEIRO = 'B'

USE SAP_DIV
GO
SELECT	VALOR_FRETE_RAT as 'FRETE_ENTR_DIRETA'
		FROM SAP_DIV.dbo.ZMMT_CONHEC_NOTA  WHERE DATA_EMIS_NOTA >= '01/01/2022' and TIPO_PARCEIRO = 'C';



USE SAP_DIV
GO
SELECT	CONHECIMENTO, ORDEM_VENDA, DATA_EMISS_CON, DATA_EMIS_NOTA, VALOR_TOT_NOTA, VALOR_FRETE_RAT as 'FRETE_TRANSFERENCIA',
TIPO_PARCEIRO FROM SAP_DIV.dbo.ZMMT_CONHEC_NOTA  WHERE DATA_EMIS_NOTA >= '01/01/2022' 


SELECT	DISTINCT(ORDEM_VENDA), ORDEM_VENDA  FROM SAP_DIV.dbo.ZMMT_CONHEC_NOTA  WHERE DATA_EMIS_NOTA >= '01/01/2022'

++++


USE SAP_DIV
GO
ALTER VIEW view_analise_frete_ov
AS
SELECT	aa.ORDEM_VENDA,
		bb.ORDEM_VENDA ORDEM_VENDA_TRANSF,
		cc.ORDEM_VENDA ORDEM_VENDA_DIR,

		bb.PARCEIRO_TRANSF PARCEIRO_TRANSF,
		bb.DATA_EMIS_CON_TRANSF DATA_EMIS_CON_TRANSF,
		bb.DATA_IMIS_NOTA_TRANSF DATA_IMIS_NOTA_TRANSF,
		bb.VALOR_TOT_NOTA_TRANSF VALOR_TOT_NOTA_TRANSF,
		bb.VALOR_FRETE_TRANSF VALOR_FRETE_TRANSF,

		cc.PARCEIRO_DIR PARCEIRO_DIR,
		cc.DATA_EMIS_CON_DIR DATA_EMIS_CON_DIR,
		cc.DATA_EMIS_NOTA_DIR DATA_EMIS_NOTA_DIR,
		cc.VALOR_TOT_NOTA_DIR VALOR_TOT_NOTA_DIR,
		cc.VALOR_FRETE_DIR VALOR_FRETE_DIR
			FROM (SELECT DISTINCT(ORDEM_VENDA) FROM SAP_DIV.dbo.ZMMT_CONHEC_NOTA  WHERE DATA_EMIS_NOTA >= '01/01/2022' AND ORDEM_VENDA IS NOT NULL) aa 
				left join (SELECT	
									DOCNUM,
									ORDEM_VENDA, 
									TIPO_PARCEIRO,
									CONHECIMENTO 'CONHECIMENTO_TRANSF', 
									DATA_EMISS_CON 'DATA_EMIS_CON_TRANSF', 
									ID_PARCEIRO 'PARCEIRO_TRANSF',
									DATA_EMIS_NOTA 'DATA_IMIS_NOTA_TRANSF', 
									VALOR_TOT_NOTA 'VALOR_TOT_NOTA_TRANSF', 
									VALOR_FRETE_RAT  'VALOR_FRETE_TRANSF'
										FROM SAP_DIV.dbo.ZMMT_CONHEC_NOTA  WHERE DATA_EMIS_NOTA >= '01/01/2022' and TIPO_PARCEIRO = 'B') bb ON (aa.ORDEM_VENDA = bb.ORDEM_VENDA)
				left join (SELECT	
									ORDEM_VENDA ORDEM_VENDA,
									CONHECIMENTO 'CONHECIMENTO_DIR', 
									DATA_EMISS_CON 'DATA_EMIS_CON_DIR', 
									ID_PARCEIRO 'PARCEIRO_DIR',
									DATA_EMIS_NOTA 'DATA_EMIS_NOTA_DIR', 
									VALOR_TOT_NOTA 'VALOR_TOT_NOTA_DIR', 
									VALOR_FRETE_RAT  'VALOR_FRETE_DIR'
										FROM SAP_DIV.dbo.ZMMT_CONHEC_NOTA  WHERE DATA_EMIS_NOTA >= '01/01/2022' and TIPO_PARCEIRO = 'C') cc ON (aa.ORDEM_VENDA = cc.ORDEM_VENDA)
			WHERE aa.ORDEM_VENDA != '';



SELECT * FROM SAP_DIV.dbo.view_analise_frete_ov



USE SAP_DIV
GO
ALTER VIEW view_analise_frete_ov_trans
AS
SELECT	aa.ORDEM_VENDA,
		bb.ORDEM_VENDA ORDEM_VENDA_TRANSF,

		bb.PARCEIRO_TRANSF PARCEIRO_TRANSF,
		lf.NAME1 NOME_TRANS_TRANSF,
		bb.DATA_EMIS_CON_TRANSF DATA_EMIS_CON_TRANSF,
		bb.DATA_IMIS_NOTA_TRANSF DATA_IMIS_NOTA_TRANSF,
		bb.VALOR_TOT_NOTA_TRANSF VALOR_TOT_NOTA_TRANSF,
		bb.VALOR_FRETE_TRANSF VALOR_FRETE_TRANSF
			FROM (SELECT DISTINCT(ORDEM_VENDA) FROM SAP_DIV.dbo.ZMMT_CONHEC_NOTA  WHERE DATA_EMIS_NOTA >= '01/01/2018' AND ORDEM_VENDA IS NOT NULL) aa 
				left join (SELECT	
									DOCNUM,
									ORDEM_VENDA, 
									TIPO_PARCEIRO,
									CONHECIMENTO 'CONHECIMENTO_TRANSF', 
									DATA_EMISS_CON 'DATA_EMIS_CON_TRANSF', 
									ID_PARCEIRO 'PARCEIRO_TRANSF',
									DATA_EMIS_NOTA 'DATA_IMIS_NOTA_TRANSF', 
									VALOR_TOT_NOTA 'VALOR_TOT_NOTA_TRANSF', 
									VALOR_FRETE_RAT  'VALOR_FRETE_TRANSF'
										FROM SAP_DIV.dbo.ZMMT_CONHEC_NOTA  WHERE DATA_EMIS_NOTA >= '01/01/2018' and TIPO_PARCEIRO = 'B') bb ON (aa.ORDEM_VENDA = bb.ORDEM_VENDA)
				left join (SELECT LIFNR, NAME1 FROM SAP_DIV.dbo.LFA1) lf ON (bb.PARCEIRO_TRANSF = lf.LIFNR)
				WHERE aa.ORDEM_VENDA != '';




USE SAP_DIV
GO
ALTER VIEW view_analise_frete_ov_dir
AS
SELECT	aa.ORDEM_VENDA,
		cc.ORDEM_VENDA ORDEM_VENDA_DIST,
		cc.PARCEIRO_DIST PARCEIRO_DIST,
		lf.NAME1 NOME_TRANS_DIST,
		cc.DATA_EMIS_CON_DIST DATA_EMIS_CON_DIST,
		cc.DATA_EMIS_NOTA_DIST DATA_EMIS_NOTA_DIST,
		cc.VALOR_TOT_NOTA_DIST VALOR_TOT_NOTA_DIST,
		cc.VALOR_FRETE_DIST VALOR_FRETE_DIST
			FROM (SELECT DISTINCT(ORDEM_VENDA) FROM SAP_DIV.dbo.ZMMT_CONHEC_NOTA  WHERE DATA_EMIS_NOTA >= '01/01/2018' AND ORDEM_VENDA IS NOT NULL) aa 
				left join (SELECT	
									ORDEM_VENDA ORDEM_VENDA,
									CONHECIMENTO 'CONHECIMENTO_DIST', 
									DATA_EMISS_CON 'DATA_EMIS_CON_DIST', 
									ID_PARCEIRO 'PARCEIRO_DIST',
									DATA_EMIS_NOTA 'DATA_EMIS_NOTA_DIST', 
									VALOR_TOT_NOTA 'VALOR_TOT_NOTA_DIST', 
									VALOR_FRETE_RAT  'VALOR_FRETE_DIST'
										FROM SAP_DIV.dbo.ZMMT_CONHEC_NOTA  WHERE DATA_EMIS_NOTA >= '01/01/2018' and TIPO_PARCEIRO = 'C') cc ON (aa.ORDEM_VENDA = cc.ORDEM_VENDA)
				left join (SELECT LIFNR, NAME1 FROM SAP_DIV.dbo.LFA1) lf ON (cc.PARCEIRO_DIST = lf.LIFNR)
				WHERE aa.ORDEM_VENDA != '';


--Historico de vendas com os valores do frente todos juntos
SELECT * FROM 
		unifort_prod.dbo.analise_historico_vendas_transporte_OV ov
	left join SAP_DIV.dbo.view_analise_frete_ov_dir di ON (ov.OV = di.ORDEM_VENDA)
	left join SAP_DIV.dbo.view_analise_frete_ov_trans tr ON (ov.OV = tr.ORDEM_VENDA);


SELECT *FROM SAP_DIV.dbo.view_analise_frete_ov_dir


--IDENTIFICANDO DADOS INCONSISTENTES NO BANCO
SELECT DISTINCT(ORDEM_VENDA) FROM SAP_DIV.dbo.ZMMT_CONHEC_NOTA
 WHERE DATA_EMIS_NOTA <= '18/11/2022' 


--DELETANDO DADOS INCONSISTENTES NO BANCO
DELETE  FROM SAP_DIV.dbo.ZMMT_CONHEC_NOTA
 WHERE ORDEM_VENDA in ('798805.', '803548.')



