
BACKUP DATABASE [query_dw] TO  DISK = N'C:\Users\BKP\query_dw.bak' 
	WITH NOFORMAT, NOINIT,  NAME = N'query_dw-Completo Banco de Dados Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

BACKUP DATABASE SAP_BSEG TO  DISK = N'C:\Users\BKP\SAP_BSEG.bak' 
	WITH NOFORMAT, NOINIT,  NAME = N'SAP_BSEG-Completo Banco de Dados Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO


BACKUP DATABASE [SAP_DIV] TO  DISK = N'C:\Users\BKP\SAP_DIV.bak' 
	WITH NOFORMAT, NOINIT,  NAME = N'SAP_DIV-Completo Banco de Dados Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO


BACKUP DATABASE [SAP_ESTOQUE] TO  DISK = N'C:\Users\BKP\SAP_ESTOQUE.bak' 
	WITH NOFORMAT, NOINIT,  NAME = N'SAP_ESTOQUE-Completo Banco de Dados Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO


BACKUP DATABASE [SAP_KONV] TO  DISK = N'C:\Users\BKP\SAP_KONV.bak' 
	WITH NOFORMAT, NOINIT,  NAME = N'SAP_KONV-Completo Banco de Dados Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO


BACKUP DATABASE [SAP_VBRP] TO  DISK = N'C:\Users\BKP\SAP_VBRP.bak' 
	WITH NOFORMAT, NOINIT,  NAME = N'SAP_VBRP-Completo Banco de Dados Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO


BACKUP DATABASE [unifort_prod] TO  DISK = N'C:\Users\BKP\unifort_prod.bak' 
	WITH NOFORMAT, NOINIT,  NAME = N'unifort_prod-Completo Banco de Dados Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

BACKUP DATABASE [WMS_DIV] TO  DISK = N'C:\Users\BKP\WMS_DIV.bak' 
	WITH NOFORMAT, NOINIT,  NAME = N'WMS_DIV-Completo Banco de Dados Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO


BACKUP DATABASE [ZMM1237] TO  DISK = N'C:\Users\BKP\ZMM1237.bak' 
	WITH NOFORMAT, NOINIT,  NAME = N'ZMM1237-Completo Banco de Dados Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO
