DECLARE @h INT;
DECLARE @m INT;
DECLARE @b INT;

SET @h = (SELECT  DATEPART (hour ,GETDATE()));
SET @m = (SELECT  DATEPART (minute ,GETDATE()));
SET @b = 1;

WHILE @b = 1
BEGIN

	IF @h >= 2 AND @m >= 30
	BEGIN
		PRINT GETDATE()
		
			BACKUP DATABASE [query_dw] TO  DISK = N'C:\Users\BKP\query_dw.bak' 	WITH NOFORMAT, NOINIT,  NAME = N'query_dw-Completo Banco de Dados Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
			BACKUP DATABASE [SAP_DIV] TO  DISK = N'C:\Users\BKP\SAP_DIV.bak' WITH NOFORMAT, NOINIT,  NAME = N'SAP_DIV-Completo Banco de Dados Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
			BACKUP DATABASE [SAP_ESTOQUE] TO  DISK = N'C:\Users\BKP\SAP_ESTOQUE.bak' WITH NOFORMAT, NOINIT,  NAME = N'SAP_ESTOQUE-Completo Banco de Dados Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
			BACKUP DATABASE [SAP_KONV] TO  DISK = N'C:\Users\BKP\SAP_KONV.bak'  WITH NOFORMAT, NOINIT,  NAME = N'SAP_KONV-Completo Banco de Dados Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
			BACKUP DATABASE [SAP_VBRP] TO  DISK = N'C:\Users\BKP\SAP_VBRP.bak' WITH NOFORMAT, NOINIT,  NAME = N'SAP_VBRP-Completo Banco de Dados Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
			BACKUP DATABASE [unifort_prod] TO  DISK = N'C:\Users\BKP\unifort_prod.bak' WITH NOFORMAT, NOINIT,  NAME = N'unifort_prod-Completo Banco de Dados Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
			BACKUP DATABASE [WMS_DIV] TO  DISK = N'C:\Users\BKP\WMS_DIV.bak' WITH NOFORMAT, NOINIT,  NAME = N'WMS_DIV-Completo Banco de Dados Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
			BACKUP DATABASE [ZMM1237] TO  DISK = N'C:\Users\BKP\ZMM1237.bak' WITH NOFORMAT, NOINIT,  NAME = N'ZMM1237-Completo Banco de Dados Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10

		PRINT GETDATE()
		BREAK
	END

	SET @h = (SELECT  DATEPART (hour ,GETDATE()));
	SET @m = (SELECT  DATEPART (minute ,GETDATE()));
	WAITFOR DELAY '00:10:00'

END